# Generated by Django 3.2 on 2021-05-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listen_first', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
