# Generated by Django 3.2 on 2021-05-26 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listen_first', '0002_testimonial_terms_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='review',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
