# Generated by Django 3.2 on 2021-05-26 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listen_first', '0003_testimonial_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='reviewed',
        ),
    ]
