# Generated by Django 3.2 on 2021-05-28 13:21

from django.db import migrations
import listen_first.models
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('listen_first', '0004_remove_testimonial_reviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='media_file',
            field=private_storage.fields.PrivateFileField(storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=listen_first.models.testimonial_path),
        ),
    ]
