# Generated by Django 3.2 on 2021-05-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listen_first', '0006_alter_testimonial_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='participant_id',
            field=models.CharField(max_length=100),
        ),
    ]
